version: "3"

services:
  redis:
    image: redis
    container_name: dns_redis
    networks:
      - dns-redis-network
    restart: "always"

  dns_cacheserver:
    build: .
    container_name: "dns_cacheserver"
    networks:
      - dns-redis-network
    environment:
      - REDIS_HOST=dns_redis
    ports:
      - "5153:5153/udp"
    restart: "always"

networks:
  dns-redis-network:
    driver: bridge